### ISSUE TITLE
add .gitignore and create a  feature branch 

### ISSUE THREAD

**Issue by SauravDas90** [pritamroy11/multi-doc-summ#2]
create a new branch called feature for making changes

provide contribute access to me and suman

gitignore should have following entries 
- .metadata
  .project
  .settings
  .classpath
  build

**Comment by pritamroy11** [comment]
access given. do what you want

**Comment by pritamroy11** [comment]
https://www.youtube.com/watch?v=V42r5REJx-M

**Comment by SauravDas90** [comment]
Issue was not with importing project, in web.xml _index.jsp_ was there but actually file was _Index.jsp_
Also updated the .gitignore file
